export const dataHeader ={
    routs:[
        {
            id:12345,
            nameRoute:"AboutUs",
            path:"/about-us"
        },
        {
            id:133565,
            nameRoute:"background",
            path:"/background"
        },
        {
            id:887665,
            nameRoute:"register",
            path:"/register"
        }
    ]
}